### ISSUE TITLE
OKQ8 Mastercard does not work

### ISSUE THREAD

**Issue by johdah** [liato/android-bankdroid#270]
Only an exclamation mark in the widget and the balance never updates.

**Comment by goober** [comment]
@johdah Could you please provide the needed data as described in https://github.com/liato/android-bankdroid/blob/master/README.rst and I will do my best to fix your problem. Can you please send the info to mathias.ahsberg [at] gmail.com

**Comment by JAGulin** [comment]
Is there a Bankdroid account type for OKQ8 Mastercard? I don't see that OKQ8 issues such cards (anymore). Maybe this issue is obsolete?

http://www.okq8.se/kort/

I might add that it works fine for me with OKQ8 Visa. But I just created the account so there's no stale info that could cause problems in my case.

**Comment by mikjo243** [comment]
OKQ8 not working for me again. 
Worked fine the other day. Then I factory reset my phone and installed bankdroid again. 

Now I get "Server certificate not trusted" for OKQ8.

**Comment by goober** [comment]
Certificate has been updated since the issue was created. Closing for now.
