### ISSUE TITLE
What is Bank.URL used for?

### ISSUE THREAD

**Issue by walles** [liato/android-bankdroid#609]
Hi!

What is `Bank.URL` used for?

The URL set by `Lansforsakringar.java` can't be accessed, but the Länsförsäkringar implementation seems to work just fine anyway.

What should this thing be set to by `Lansforsakringar.java`? Can it be set to `null`?

**Comment by goober** [comment]
The url is a legacy feature originated from the time when most banks had a separate mobile web page. Then you could access that page directly from within bankdroid. Since most banks now have removed the mobile friendly web page and uses their mobile apps instead this feature has been disabled for more and more banks. Länsförsäkringar is one of them. So it is not relevant to keep a broken URL for that bank anymore.

Furthermore, the check for whether the web view is enable is done by `Bank#isWebViewEnabled`. If you are going to touch the url for Länsförsäkringar to clean up the code a bit. Please take a quick look at the method above and add a `null` check on the url while your at it.
