### ISSUE TITLE
Meaning of "legacy"

### ISSUE THREAD

**Issue by DamienCassou** [liato/android-bankdroid#628]
I'm interested in porting the "Nordea" Java code you have to http://weboob.org/ (Python). I saw the [https://github.com/liato/android-bankdroid/blob/master/bankdroid-legacy/src/main/java/com/liato/bankdroid/banking/banks/nordea/Nordea.java](`Nordea.java`) class but it's in the "legacy" directory. Is bankdroid still using this class? Is there another class I need to  port except the classes referenced by this one?

Thanks

**Comment by goober** [comment]
Hi. We have a long term goal of extracting out the data fetching from the source systems, e.g. nordea, and the data storing/representation within Bankdroid. Since all fetching / storing / representation is done through the Bank.java class today we have moved everything into a separate module so we can have an incremental rollover to the new implementation. So everything is still used within the legacy module.
