### ISSUE TITLE
Make crashlytics optional

### ISSUE THREAD

**Issue by goober** [liato/android-bankdroid#631]
Move crashlytics into separate module and wrap it into a logging interface to make it optional.
- [x] Use Timber for logging
- [ ] Wrap Fabric Answers into an `EventLogger`
- [ ] Fire anonymous events on successfully bank updates and failed updates to track bank usage
- [ ] Extract Crashlytics Timber Tree to its own module.
- [ ] Add build parameter to ignore crashlytics module

**Comment by walles** [comment]
Maybe using this?

https://github.com/JakeWharton/timber

I've used it and like it, it even comes with custom Android Lint rules!

**Comment by goober** [comment]
Looks promising. I will take a look

**Comment by robho** [comment]
When this is done, will it be possible to make an android build without crashlytics?

I'm asking because F-Droid needs this to make Bankdroid available in its repository (see #450). Currently they have some hairy sed preprocessing which removes crashlytics from the source before building Bankdroid.

(Bankdroid is a few releases behind on F-Droid and automatic builds of new releases were disabled when crashlytics appeared in Bankdroid. If a crashlytics-free release of Bankdroid would be possible I think the Bankdroid experience would be better for F-Droid users. Probably not many Bankdroid users use F-Droid, but thought I'd mention it anyway :-))

**Comment by goober** [comment]
My idea is to move out crashlytics-related code into a new module e.g. `logging-crashlytics`, load it dynamically through javas [ServiceLoader](http://docs.oracle.com/javase/6/docs/api/java/util/ServiceLoader.html), with a local logging as a fallback.
In addition to that I am planning to add a build property to exclude the `logging-crashlytics`-module when you build the artifacts.

@robho could that be a working solution for you?

**Comment by robho** [comment]
Thanks for the clarification. It sounds good to me, but I don't know much about the android build system or F-Droid packaging.

Go for what you're planning and I'll try to understand your changes and see if I can help get the F-Droid builds updated..

**Comment by goober** [comment]
Basically you should be able to run `./gradlew assembleRelease -PignoreCrashlytics` and bankdroid should be built without a dependency to crashlytics

**Comment by IzzySoft** [comment]
Any progress concerning Crashlytics? This issue was last updated almost 2 years ago and possibly forgotten about?

**Comment by IzzySoft** [comment]
Ah! I almost forgot about this one – now it's comple… wait:

```gradle
    compile('com.crashlytics.sdk.android:crashlytics:2.6.5@aar') {
        transitive = true;
    }
```

So I guess it's rather "wontfix" then? :cry:
